server:
  port: 9001

spring:
  application:
    name: twitter.backend
  datasource:
    url: jdbc:mysql://localhost:3306/twitterdb
    username: root
    password: edmondlin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true